#!/bin/bash

###############################################################################
# GUÍA RÁPIDA: Cómo ejecutar el script de síntomas
###############################################################################

echo "📋 PASO 1: Obtener tu token de administrador"
echo ""
echo "Opción A - Si ya tienes acceso al dashboard admin:"
echo "  1. Inicia sesión en el dashboard"
echo "  2. Abre las DevTools (F12)"
echo "  3. Ve a Application/Storage → Local Storage"
echo "  4. Busca 'authToken' o similar"
echo "  5. Copia el valor"
echo ""
echo "Opción B - Login via API:"
echo ""
echo "curl -X POST https://api.munpa.online/api/auth/admin/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"email\": \"tu_email_admin@munpa.com\","
echo "    \"password\": \"tu_password\""
echo "  }'"
echo ""
echo "---"
echo ""
echo "📋 PASO 2: Configurar el token en el script"
echo ""
echo "Edita el archivo scripts/populate-symptoms.sh y reemplaza:"
echo "  ADMIN_TOKEN=\"TU_ADMIN_TOKEN_AQUI\""
echo ""
echo "Por:"
echo "  ADMIN_TOKEN=\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\""
echo ""
echo "---"
echo ""
echo "📋 PASO 3: Ejecutar el script"
echo ""
echo "chmod +x scripts/populate-symptoms.sh"
echo "./scripts/populate-symptoms.sh"
echo ""
echo "---"
echo ""
echo "🎯 O usa Node.js:"
echo ""
echo "1. Instala axios:"
echo "   npm install axios"
echo ""
echo "2. Edita scripts/populate-symptoms.js con tu token"
echo ""
echo "3. Ejecuta:"
echo "   node scripts/populate-symptoms.js"
echo ""
